"""add is_delete in product model

Revision ID: 89ead910953e
Revises: cddbe3d4224e
Create Date: 2026-01-11 19:56:49.885050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ead910953e'
down_revision: Union[str, Sequence[str], None] = 'cddbe3d4224e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку, но временно разрешаем NULL
    op.add_column('products', sa.Column('is_delete', sa.Boolean(), nullable=True))
    
    # 2. Устанавливаем значение False для всех существующих записей
    # Используем чистый SQL внутри миграции
    op.execute("UPDATE products SET is_delete = False")
    
    # 3. Теперь, когда пустых значений нет, накатываем ограничение NOT NULL
    op.alter_column('products', 'is_delete', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_delete')
    # ### end Alembic commands ###
