"""Fix is_delete column in category

Revision ID: b683cbbf3d4d
Revises: e7d10eb879fb
Create Date: 2026-03-17 17:17:06.114771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b683cbbf3d4d'
down_revision: Union[str, Sequence[str], None] = 'e7d10eb879fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
