"""add is_admin flag into User model

Revision ID: cddbe3d4224e
Revises: b31cc89a7b84
Create Date: 2026-01-11 16:54:48.403425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cddbe3d4224e'
down_revision: Union[str, Sequence[str], None] = 'b31cc89a7b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку как допускающую NULL
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # 2. Проставляем дефолтное значение False всем существующим юзерам
    op.execute("UPDATE users SET is_admin = False")
    
    # 3. Теперь, когда пустых ячеек нет, ставим ограничение NOT NULL
    op.alter_column('users', 'is_admin', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
