"""Added soft-delete into category model

Revision ID: e7d10eb879fb
Revises: 436b3e608af6
Create Date: 2026-02-04 02:07:11.858535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d10eb879fb'
down_revision: Union[str, Sequence[str], None] = '436b3e608af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "categories",
        sa.Column(
            "is_delete",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false")
        )
    )

    op.alter_column(
        "categories",
        "is_delete",
        server_default=None
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_delete')
    # ### end Alembic commands ###
